version: 2.1
jobs:
  build:
    environment:
      SERVER_IP_ADDRESS: 104.236.101.13
      DOKKU_APP: circlecidemo
      TRAVIS: "false"
    docker:
        - image: circleci/node:7.10
  
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}

      - run: yarn test

      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      - run: echo ${SERVER_IP_ADDRESS}
      - run: echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      # DEPLOY "Staging" App:
      - run: sh bin/deploy.sh